spring.application.name=sourcecode

server.port=8000

spring.mvc.view.prefix=/WEB-INF/views/pages/
spring.mvc.view.suffix=.jsp

spring.datasource.url=jdbc:mysql://localhost:3308/ayush_project?useUnicode=true&characterEncoding=UTF-8
spring.datasource.username=root
spring.datasource.password=root
#spring.jpa.hibernate.ddl-auto=update
#spring.jpa.show-sql=true

spring.http.encoding.charset=UTF-8
